version: "3.9"

services:
    backend:
        container_name: ace2-gui-backend
        build:
            context: .
            dockerfile: ./backend/Dockerfile
        volumes:
            - "./backend/app:/app"
        ports:
            - 8888:80
        command: /start-reload.sh

    frontend:
        container_name: ace2-gui-frontend
        build:
            context: .
            dockerfile: ./frontend/Dockerfile.dev
        volumes:
            - "./frontend/app:/app"
            - "/app/node_modules"
        ports:
            - 9999:8080